
package vista;
import controlador.EjercicioController;
import controlador.RutinaController;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import modelo.NivelRutina;
import java.util.ArrayList;
import modelo.Ejercicio;
import modelo.Rutina;

public class CrearRutinaFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CrearRutinaFrame.class.getName());
    private Usuario usuario;
    private RutinaController rutinaController;
    private EjercicioController ejercicioController;
    private DefaultTableModel modeloDisponibles;
    private DefaultTableModel modeloRutina;
    private ArrayList<Ejercicio> ejerciciosDisponibles;
    private ArrayList<Ejercicio> ejerciciosSeleccionados;

    /**
     * Creates new form CrearRutinaFrame
     */
    public CrearRutinaFrame(Usuario usuario) {
        initComponents();
        cargarNiveles();
        this.usuario = usuario;
        rutinaController = new RutinaController();
        ejercicioController = new EjercicioController();
        ejerciciosDisponibles = new ArrayList<>();
        ejerciciosSeleccionados = new ArrayList<>();

        modeloDisponibles = new DefaultTableModel();
        modeloDisponibles.addColumn("Nombre");
        modeloDisponibles.addColumn("Grupo Muscular");
        modeloRutina = new DefaultTableModel();
        modeloRutina.addColumn("Nombre");
        modeloRutina.addColumn("Grupo Muscular");
        tblDisponibles.setModel(modeloDisponibles);
        tblRutina.setModel(modeloRutina);
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Crear Rutina");
        cargarEjercicios();
    }
    private void cargarNiveles() {
        cboNivel.removeAllItems();
        for (NivelRutina nivel : NivelRutina.values()) {
            cboNivel.addItem(nivel.name());
        }
    }

    private void cargarEjercicios() {
        modeloDisponibles.setRowCount(0);
        ejerciciosDisponibles.clear();
        ejerciciosDisponibles.addAll(
            ejercicioController.obtenerEjercicios());
        for (Ejercicio ejercicio : ejerciciosDisponibles) {
            modeloDisponibles.addRow(new Object[]{
            ejercicio.getNombre(),
            ejercicio.getGrupoMuscular()
            });
        }
    }
    private void cargarTablas() {
        modeloDisponibles.setRowCount(0);
        modeloRutina.setRowCount(0);
        for (Ejercicio ejercicio : ejerciciosDisponibles) {
            modeloDisponibles.addRow(new Object[]{
            ejercicio.getNombre(),
            ejercicio.getGrupoMuscular()
            });
        }
        for (Ejercicio ejercicio : ejerciciosSeleccionados) {  
            modeloRutina.addRow(new Object[]{
                ejercicio.getNombre(),
                ejercicio.getGrupoMuscular()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtNombreRutina = new javax.swing.JTextField();
        lblDisponible = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDisponibles = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        lblEjerciciosR = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblRutina = new javax.swing.JTable();
        btnQuitar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cboNivel = new javax.swing.JComboBox<>();
        lblNivel = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("CREAR RUTINA");

        txtNombre.setText("Nombre de la rutina:");

        lblDisponible.setText("Ejercicios disponibles");
        lblDisponible.setToolTipText("");

        tblDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Grupo Muscular"
            }
        ));
        jScrollPane2.setViewportView(tblDisponibles);

        jScrollPane1.setViewportView(jScrollPane2);

        btnAgregar.setText("Agregar →");
        btnAgregar.addActionListener(this::btnAgregarActionPerformed);

        lblEjerciciosR.setText("Ejercicios de la rutina");

        tblRutina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Grupo Muscular"
            }
        ));
        jScrollPane4.setViewportView(tblRutina);

        btnQuitar.setText("← Quitar");
        btnQuitar.addActionListener(this::btnQuitarActionPerformed);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        cboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboNivel.addActionListener(this::cboNivelActionPerformed);

        lblNivel.setText("Nivel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre)
                            .addComponent(cboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNivel)
                            .addComponent(lblDisponible)
                            .addComponent(lblEjerciciosR)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(109, 109, 109)
                                        .addComponent(btnQuitar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGuardar)
                                        .addGap(123, 123, 123)
                                        .addComponent(btnCancelar))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addComponent(btnAgregar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(lblTitulo)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreRutina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDisponible)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addGap(5, 5, 5)
                .addComponent(lblEjerciciosR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuitar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        RutinasFrame rutinas = new RutinasFrame(usuario);
        rutinas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void cboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNivelActionPerformed
     
    }//GEN-LAST:event_cboNivelActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       int fila = tblDisponibles.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un ejercicio.");
        return;
        }   
        Ejercicio ejercicio = ejerciciosDisponibles.get(fila);
        ejerciciosSeleccionados.add(ejercicio);
        ejerciciosDisponibles.remove(fila);
        cargarTablas();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        int fila = tblRutina.getSelectedRow();
        if (fila == -1) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Seleccione un ejercicio de la rutina.");
        return;
        }
        Ejercicio ejercicio = ejerciciosSeleccionados.get(fila);
        ejerciciosDisponibles.add(ejercicio);
        ejerciciosSeleccionados.remove(fila);
        cargarTablas();
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String nombre = txtNombreRutina.getText().trim();
        if (nombre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Ingrese el nombre de la rutina.");
        return;
        }
        if (ejerciciosSeleccionados.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Debe agregar al menos un ejercicio.");
        return;
        }
        NivelRutina nivel = NivelRutina.valueOf(
            cboNivel.getSelectedItem().toString());
        Rutina rutina = new Rutina(nombre, nivel);
        for (Ejercicio ejercicio : ejerciciosSeleccionados) {
            rutina.agregarEjercicio(ejercicio);
        }      
        rutinaController.agregarRutina(rutina);
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Rutina creada correctamente.");
        RutinasFrame rutinas = new RutinasFrame(usuario);
        rutinas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
        System.out.println("CreaRutinaFrame debe abrirse desde el menú principal.");
    });
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cboNivel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDisponible;
    private javax.swing.JLabel lblEjerciciosR;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblDisponibles;
    private javax.swing.JTable tblRutina;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JTextField txtNombreRutina;
    // End of variables declaration//GEN-END:variables
}
