
package vista;

import controlador.EjercicioController;
import modelo.Ejercicio;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;

public class EjerciciosFrame extends javax.swing.JFrame {
    private DefaultTableModel modeloTabla;
    private EjercicioController controlador;
    private Usuario usuario;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EjerciciosFrame.class.getName());

    /**
     * Creates new form EjerciciosFrame
     */
    public EjerciciosFrame(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        controlador = new EjercicioController();
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Grupo Muscular");
        tblEjercicios.setModel(modeloTabla);
        setLocationRelativeTo(null);
        setTitle("Catálogo de Ejercicios");
        cargarEjercicios();
    }
    private void cargarEjercicios() {
        modeloTabla.setRowCount(0);
    for (Ejercicio ejercicio : controlador.obtenerEjercicios()) {
        modeloTabla.addRow(new Object[]{
            ejercicio.getNombre(),
            ejercicio.getGrupoMuscular()
        });
    }
}
    /**
 * Obtiene el ejercicio seleccionado en la tabla.
 *
 * @return Ejercicio seleccionado o null.
 */
    private Ejercicio obtenerEjercicioSeleccionado() {
        int fila = tblEjercicios.getSelectedRow();
        if (fila == -1) {
            return null;
        }
        String nombre = modeloTabla.getValueAt(fila, 0).toString();
        return controlador.buscarEjercicio(nombre);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblNombreEjercicio = new javax.swing.JLabel();
        lblGrupo = new javax.swing.JLabel();
        lblGrupoMuscular = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        lblYoutube = new javax.swing.JLabel();
        lblLinkYoutube = new javax.swing.JLabel();
        btnVideo = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEjercicios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("CATÁLOGO DE EJERCICIOS");

        jLabel1.setText("Buscar:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(this::btnBuscarActionPerformed);

        lblNombre.setText("Nombre:");

        lblGrupo.setText("Grupo Muscular:");

        lblDescripcion.setText("Descripción:");

        txtDescripcion.setEditable(false);

        lblYoutube.setText("Youtube:");
        lblYoutube.setToolTipText("");

        btnVideo.setText("Ver Video");
        btnVideo.addActionListener(this::btnVideoActionPerformed);

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(this::btnRegresarActionPerformed);

        tblEjercicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEjercicios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEjerciciosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblEjercicios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnVideo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblNombre)
                                        .addComponent(lblGrupo)
                                        .addComponent(lblDescripcion)
                                        .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblYoutube)))
                                .addGap(74, 74, 74)
                                .addComponent(btnRegresar))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addComponent(lblLinkYoutube)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGrupoMuscular)
                            .addComponent(lblNombreEjercicio))))
                .addGap(0, 130, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lblNombreEjercicio)
                        .addGap(34, 34, 34)
                        .addComponent(lblGrupoMuscular))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblNombre)
                .addGap(10, 10, 10)
                .addComponent(lblGrupo)
                .addGap(18, 18, 18)
                .addComponent(lblDescripcion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblYoutube)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVideo)
                    .addComponent(btnRegresar))
                .addGap(14, 14, 14)
                .addComponent(lblLinkYoutube)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVideoActionPerformed
    Ejercicio ejercicio = obtenerEjercicioSeleccionado();
        if (ejercicio != null) {
            controlador.abrirVideo(ejercicio);
        }
    }//GEN-LAST:event_btnVideoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       String nombre = txtBuscar.getText().trim();
        for (int i = 0; i < modeloTabla.getRowCount(); i++) {
        if (modeloTabla.getValueAt(i, 0).toString()
                .equalsIgnoreCase(nombre)) {
            tblEjercicios.setRowSelectionInterval(i, i);
            tblEjerciciosMouseClicked(null);
            return;
        }
    }
        JOptionPane.showMessageDialog(
            this,
            "Ejercicio no encontrado.");
    
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        System.out.println("Botón Regresar presionado");
    MenuPrincipalFrame menu = new MenuPrincipalFrame(usuario);
    menu.setVisible(true);
    dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void tblEjerciciosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEjerciciosMouseClicked
      Ejercicio ejercicio = obtenerEjercicioSeleccionado();
        if (ejercicio != null) {
            lblNombreEjercicio.setText(ejercicio.getNombre());
            lblGrupoMuscular.setText(
            ejercicio.getGrupoMuscular().toString());
            txtDescripcion.setText(
            ejercicio.getDescripcion());
        }
    }//GEN-LAST:event_tblEjerciciosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        System.out.println("EjerciciosFrame debe abrirse desde el menú principal.");
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnVideo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblGrupo;
    private javax.swing.JLabel lblGrupoMuscular;
    private javax.swing.JLabel lblLinkYoutube;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreEjercicio;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblYoutube;
    private javax.swing.JTable tblEjercicios;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtDescripcion;
    // End of variables declaration//GEN-END:variables
}
