
package vista;

import modelo.Usuario;
import modelo.Cliente;

public class MenuPrincipalFrame extends javax.swing.JFrame {
    private Usuario usuario;

    public MenuPrincipalFrame(Usuario usuario) {

        initComponents();
        this.usuario = usuario;
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Sistema Fidness");
        cargarInformacionUsuario();
    }
    private void cargarInformacionUsuario() {
    lblNombre.setText(usuario.getNombre());
    if (usuario instanceof Cliente cliente) {
        lblTipo.setText(
                cliente.getTipoMembresia().toString());
    } else {
        lblTipo.setText("Administrador");
    }
}
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalFrame.class.getName());

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipalFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblMembresia = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblPie1 = new javax.swing.JLabel();
        lblPie2 = new javax.swing.JLabel();
        btnEjercicios = new javax.swing.JButton();
        btnRutinas = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setText("GIMNASIO FIDNESS");

        lblBienvenido.setText("Bienvenido:");

        lblMembresia.setText("Membresía:");

        lblPie1.setText("Sistema de Gestión de Rutinas y Reservas");

        lblPie2.setText("Proyecto Final");

        btnEjercicios.setText("Consultar Ejercicios");
        btnEjercicios.addActionListener(this::btnEjerciciosActionPerformed);

        btnRutinas.setText("Mis Rutinas");
        btnRutinas.addActionListener(this::btnRutinasActionPerformed);

        btnReservas.setText("Reservar Clase");
        btnReservas.addActionListener(this::btnReservasActionPerformed);

        btnSalir.setText("Cerrar Sesión");
        btnSalir.addActionListener(this::btnSalirActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblTitulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblBienvenido)
                            .addComponent(lblMembresia)
                            .addComponent(lblTipo)
                            .addComponent(lblPie1)
                            .addComponent(lblPie2)
                            .addComponent(btnEjercicios)
                            .addComponent(btnRutinas)
                            .addComponent(btnReservas)
                            .addComponent(btnSalir))))
                .addContainerGap(230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNombre)
                .addGap(18, 18, 18)
                .addComponent(lblMembresia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTipo)
                .addGap(45, 45, 45)
                .addComponent(btnEjercicios)
                .addGap(18, 18, 18)
                .addComponent(btnRutinas)
                .addGap(18, 18, 18)
                .addComponent(btnReservas)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(lblPie1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPie2)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       LoginFrame login = new LoginFrame();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnEjerciciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjerciciosActionPerformed
      EjerciciosFrame ejercicios = new EjerciciosFrame(usuario);
      ejercicios.setVisible(true);
      dispose();
    }//GEN-LAST:event_btnEjerciciosActionPerformed

    private void btnRutinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutinasActionPerformed
        RutinasFrame rutinas = new RutinasFrame(usuario);
        rutinas.setLocationRelativeTo(null);
        rutinas.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRutinasActionPerformed

    private void btnReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasActionPerformed
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Módulo de reservas en desarrollo.");
    }//GEN-LAST:event_btnReservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjercicios;
    private javax.swing.JButton btnReservas;
    private javax.swing.JButton btnRutinas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblMembresia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPie1;
    private javax.swing.JLabel lblPie2;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
